language: android

script:
    - git fetch origin --tags
    - make debug

git:
    submodules: true

jdk:
    - oraclejdk8

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
before_install:
    - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin

install:
    - echo y | sdkmanager 'ndk-bundle'
    - echo y | sdkmanager 'cmake;3.6.4111459'
    - echo y | sdkmanager 'platform-tools'
    - echo y | sdkmanager 'build-tools;27.0.3'
    - echo y | sdkmanager 'platforms;android-27'
